# Generated by Django 4.1.3 on 2022-11-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('shed_preb', models.CharField(max_length=20)),
            ],
        ),
    ]
