# Generated by Django 4.1.3 on 2022-11-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gridload', '0002_pdbshed_rebshed_remove_gridload_shed_pdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridLoad_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madunaghat', models.CharField(max_length=40)),
                ('madunaghat1', models.IntegerField()),
                ('hathazari', models.CharField(max_length=20)),
                ('hathazari1', models.IntegerField()),
                ('baklia', models.CharField(max_length=20)),
                ('baklia1', models.IntegerField()),
                ('khulshi', models.CharField(max_length=20)),
                ('khulshi1', models.IntegerField()),
                ('halishahor', models.CharField(max_length=20)),
                ('halishahor1', models.IntegerField()),
                ('Agrabad', models.CharField(max_length=20)),
                ('Agrabad1', models.IntegerField()),
                ('chandraghuna', models.CharField(max_length=20)),
                ('chandraghuna1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MadunaghatREB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowapara', models.IntegerField()),
                ('CUET', models.IntegerField()),
                ('gridName', models.ForeignKey(choices=[('nowapara', 'nowapara'), ('Cuet', 'Cuet')], default=False, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='gridload.gridload')),
            ],
        ),
    ]
