# Generated by Django 4.1.3 on 2022-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_reb', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='khulshi_PDBShed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_pdb', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='khulshiGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
            ],
        ),
    ]
