# Generated by Django 4.1.3 on 2022-11-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bsrm',
            old_name='shed_reb',
            new_name='bsrm',
        ),
    ]
