# Generated by Django 4.1.3 on 2022-11-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0002_rename_shed_reb_bsrm_bsrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('shed_reb', models.CharField(max_length=20)),
                ('bsrm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='All_Reb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUET', models.CharField(max_length=20)),
                ('Nowapara', models.CharField(max_length=20)),
                ('HMSteel', models.CharField(max_length=20)),
                ('Sodor', models.CharField(max_length=20)),
                ('Ukiya', models.CharField(max_length=20)),
                ('Teknaf', models.CharField(max_length=20)),
                ('chokoria', models.CharField(max_length=20)),
                ('Patiya', models.CharField(max_length=20)),
                ('Lohagora', models.CharField(max_length=20)),
                ('Chondanaish', models.CharField(max_length=20)),
                ('keranirhat', models.CharField(max_length=20)),
                ('Chokoriya', models.CharField(max_length=20)),
                ('Moheskhali', models.CharField(max_length=20)),
                ('CoalPower', models.CharField(max_length=20)),
                ('Singapur', models.CharField(max_length=20)),
                ('Ranguniya', models.CharField(max_length=20)),
                ('Kodala', models.CharField(max_length=20)),
                ('Fotikchori', models.CharField(max_length=20)),
                ('Boalkhali', models.CharField(max_length=20)),
                ('Anowara', models.CharField(max_length=20)),
                ('Bashkhali', models.CharField(max_length=20)),
                ('Potiya', models.CharField(max_length=20)),
                ('Doom', models.CharField(max_length=20)),
                ('Bariryarhat', models.CharField(max_length=20)),
                ('grid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='loadinput.allgrid')),
            ],
        ),
    ]
