# Generated by Django 4.1.3 on 2022-11-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0004_remove_allgrid_bsrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakliaGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HalishahorGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HathazariGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MadunaghatGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='khulshigrid',
            name='BSRM',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='khulshigrid',
            name='shed_pdb',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='khulshigrid',
            name='grid_load',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
