# Generated by Django 4.1.3 on 2022-11-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0006_chandroghuna_coxbazar_duhazari_matarbari_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matarbari',
            new_name='ChandroghunaGrid',
        ),
        migrations.RenameModel(
            old_name='Chandroghuna',
            new_name='CoxBazarGrid',
        ),
        migrations.RenameModel(
            old_name='CoxBazar',
            new_name='DuhazariGrid',
        ),
        migrations.RenameModel(
            old_name='Duhazari',
            new_name='MatarbariGrid',
        ),
    ]
