# Generated by Django 4.1.3 on 2022-11-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0007_rename_matarbari_chandroghunagrid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKS132kvGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BarairhatGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BarauliaGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JuldaGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KalurghatGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KaptaiGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KhagrachariGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KsrmGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MSMLGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RampurGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RanghamatiGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SASMGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShahmirpurGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShikalbhahaGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SholoshahorGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TKGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.CharField(max_length=20)),
                ('shed_pdb', models.CharField(max_length=20)),
                ('reb_shed', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='AllGrid',
            new_name='AgrabadGrid',
        ),
        migrations.RenameField(
            model_name='agrabadgrid',
            old_name='shed_reb',
            new_name='reb_shed',
        ),
        migrations.RenameField(
            model_name='hathazarigrid',
            old_name='reb_shed',
            new_name='shed_reb',
        ),
        migrations.AlterField(
            model_name='all_reb',
            name='grid',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='loadinput.hathazarigrid'),
        ),
    ]
