# Generated by Django 4.1.3 on 2022-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0008_aks132kvgrid_barairhatgrid_barauliagrid_juldagrid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASK230KVGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BSRM230KVGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPH230KVGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MirashoraiEZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_load', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
