# Generated by Django 4.1.3 on 2022-11-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0009_ask230kvgrid_bsrm230kvgrid_gph230kvgrid_mirashoraiez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madunaghatgrid',
            name='grid_load',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='madunaghatgrid',
            name='reb_shed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='madunaghatgrid',
            name='shed_pdb',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Madunaghat_Reb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUET', models.PositiveIntegerField()),
                ('Nowapara', models.PositiveIntegerField()),
                ('grid', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='loadinput.hathazarigrid')),
            ],
        ),
    ]
