# Generated by Django 4.1.3 on 2022-11-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0011_chandroghuna_reb_alter_chandroghunagrid_grid_load_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chandroghuna_reb',
            old_name='reb_shed',
            new_name='Kodala',
        ),
        migrations.RenameField(
            model_name='chandroghuna_reb',
            old_name='shed_pdb',
            new_name='Rangunia',
        ),
    ]
