# Generated by Django 4.1.3 on 2022-11-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0012_rename_reb_shed_chandroghuna_reb_kodala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chandroghuna_reb',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loadinput.chandroghunagrid'),
        ),
    ]
