# Generated by Django 4.1.3 on 2022-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadinput', '0016_rename_grid_load_agrabadgrid_grid_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khulshigrid',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
